Repository filecoin-project/venus, pull requests merged in 2019-09, with the labels that each got.

#3263 Add "mining add-piece" command
  commands/mining.go
  commands/mining_daemon_test.go
  porcelain/api.go
  porcelain/sectorbuilder.go
  porcelain/sectorbuilder_test.go
  tools/fast/action_mining.go
Labels: RFM

#3131 Allow larger runs in RLE+
  rleplus/rleplus.go
  rleplus/rleplus_test.go
Labels: RFM

#3424 Generate one ticket per null block
  consensus/election.go
  consensus/election_test.go
  consensus/expected.go
  consensus/expected_test.go
  consensus/testing.go
  mining/block_generate.go
  mining/scheduler.go
  mining/scheduler_test.go
  mining/testing.go
  mining/worker.go
  mining/worker_test.go
  node/block_propagate_test.go
  testhelpers/consensus.go
  types/ticket.go
  types/tipset.go
  types/tipset_test.go
Labels: protocol breaking ⚠️

#3438 Change HAMT bitwidth to 5 for both global state tree and actor state
  actor/storage.go
  state/tree.go
Labels: protocol breaking ⚠️

#3453 Remove lookback from chain sampling for PoSt challenge seed.
  chain/get_ancestors.go
  chain/get_ancestors_test.go
  chain/syncer.go
  consensus/expected.go
  node/node.go
  plumbing/cst/chain_state.go
  plumbing/msg/waiter.go
  sampling/chain_randomness.go
  sampling/chain_randomness_test.go
Labels: protocol breaking ⚠️

#3471 fix a bug where CID != Seralized IPLD signed message
  types/signed_message.go
  types/signed_message_test.go
Labels: C-bug
