Repository filecoin-project/venus, pull requests merged in 2019-02, with the labels that each got.

#1795 Part 1/3 Tickets --> Signed tickets #1054
  api/impl/mining.go
  config/config.go
  config/config_test.go
  mining/worker.go
  mining/worker_test.go
  node/node.go
  node/node_test.go
  node/testing.go
  repo/fsrepo_test.go
  wallet/wallet.go
Labels: A-consensus, request-for-input

#2007 doc: add `jq` ad dependency
  README.md
Labels: RFM

#2033 Add note to README about slow proof parameter download or generation in deps.
  README.md
Labels: RFM

#1864 Update FAST retrieval test to work with miner payments
  tools/fast/series/series_sendfilecoindefaults.go
  tools/fast/tests/retrieval_test.go
Labels: A-FAST, RFM

#2006 rust: stop install script if anything fails
  scripts/install-rust-proofs.sh
Labels: RFM

#2015 Feat/payment channel porcelain 1942
  api/impl/paych.go
  api/paych.go
  commands/payment_channel.go
Labels: C-technical-debt

#2051 Feat/deal propose sigs
  protocol/storage/client.go
  protocol/storage/client_test.go
  protocol/storage/miner.go
  protocol/storage/miner_test.go
  protocol/storage/types.go
Labels: PROTOCOL BREAKING

#2047 Feat/wallet balance porcelain 1797
  api/address.go
  api/impl/address.go
  commands/address.go
  plumbing/api.go
  porcelain/api.go
  porcelain/wallet.go
  porcelain/wallet_test.go
Labels: C-technical-debt

#2039 Update swarm.go
  commands/swarm.go
Labels: RFM
