Repository filecoin-project/venus, pull requests merged in 2023-08, with the labels that each got.

#6063 remove MinPeerThreshold in bootstrap config because it is not used /删除MinPeerThreshold字段从bootstrap配置，没有用到
  app/node/test/builder.go
  fixtures/networks/butterfly.go
  fixtures/networks/calibration.go
  fixtures/networks/forcenet.go
  fixtures/networks/hyperspace.go
  fixtures/networks/integrationtestnet.go
  fixtures/networks/interopnet.go
  fixtures/networks/mainnet.go
  fixtures/networks/net_2k.go
  fixtures/networks/wallaby.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/testing.go
Labels: C-enhancement

#5989 [venus] add design doc of sync/添加同步设计文档
  documentation/zh/sync.md
Labels: C-docs

#6100 Make execution trace configurable via env variable venus / 通过VENUS_EXEC_TRACE_CACHE环境变量谁知trace缓存大小
  app/submodule/syncer/syncer_submodule.go
  pkg/chainsync/syncer/syncer_integration_test.go
  pkg/chainsync/syncer/syncer_test.go
  pkg/messagepool/messagepool_test.go
  pkg/statemanger/state_manger.go
Labels: C-enhancement

#6101 fix: ethtypes: handle length overflow case / 处理rlp长度越界问题
  venus-shared/actors/types/rlp.go
  venus-shared/actors/types/rlp_test.go
Labels: C-bug

#6104 fix duplicate actor events / 解决以太坊event 日志重复问题
  app/submodule/eth/eth_event_api.go
  pkg/events/filter/index.go
  pkg/events/filter/index_test.go
Labels: C-bug, C-enhancement

#6107 Fix/wallet balance cmd
  cmd/address.go
  cmd/address_integration_test.go
  pkg/events/filter/index.go
Labels: nv21

#6110 add check before write badger / 添加检查已经存在，在写入之前
  venus-shared/blockstore/badger.go
Labels: C-enhancement, nv21

#6113 set gcConfidence = 2 * constants.ForkLengthThreshold / 设置gcConfidence的值为2 * constants.ForkLengthThreshold
  app/submodule/eth/eth_api.go
  app/submodule/eth/eth_event_api.go
  pkg/events/events.go
Labels: C-bug, nv21

#6111 fix: add existing nonce error
  app/submodule/mpool/mpool_submodule.go
  pkg/messagepool/messagepool.go
Labels: nv21

#6120 chore: Output log when FVM_CONCURRENCY value is too large
  pkg/vm/vmcontext/execution.go
Labels: nv21

#6121 feat: migrate to boxo
  app/node/test/node.go
  app/submodule/blockstore/blockstore_api.go
  app/submodule/dagservice/blockservice_submoodule.go
  app/submodule/network/network_submodule.go
  app/submodule/storagenetworking/storage_networking_submodule.go
  app/submodule/syncer/syncer_submodule.go
  go.mod
  go.sum
  pkg/chain/message_store.go
  pkg/chain/message_store_test.go
  pkg/chain/store.go
  pkg/chain/waiter.go
  pkg/chainsync/syncer/syncer.go
  pkg/fork/fork.go
  pkg/genesis/genesis.go
  pkg/repo/fsrepo.go
  pkg/util/dag/dag.go
  pkg/util/dag/dag_test.go
  pkg/util/dag/oldpath/oldresolver/resolver.go
  pkg/vm/vmcontext/actor_store_test.go
  tools/conformance/runner.go
  tools/gengen/util/gengen.go
  tools/gengen/util/gengen_test.go
  venus-devtool/go.mod
  venus-devtool/go.sum
  venus-shared/actors/policy/policy.go
  venus-shared/actors/policy/policy.go.template
  venus-shared/blockstore/badger.go
  venus-shared/blockstore/blockstore.go
  venus-shared/blockstore/view_blockstore.go
  venus-shared/compatible-checks/api-checksum.txt
  venus-shared/compatible-checks/api-diff.txt
  venus-shared/compatible-checks/api-perm.txt
Labels: nv21

#6117 Auto-resume interrupted snapshot imports / 自动重链快照导入失败时
  cmd/import.go
  pkg/httpreader/resumable.go
Labels: C-enhancement

#6125 fix: DecodeRLP can panic
  venus-shared/actors/types/rlp.go
Labels: nv21

#6126 feat: vm: allow raw cbor in state and use the new go-multicodec
  go.mod
  pkg/chain/store.go
  pkg/fork/fork.go
  venus-shared/blockstore/copy.go
Labels: nv21

#6124 Feat/invert validation switch checks
  app/submodule/mpool/mpool_submodule.go
  pkg/messagepool/messagepool.go
Labels: nv21

#6118 optimize LoadTipSetMessage / 优化LoadTipSetMessage
  pkg/chain/message_store.go
Labels: C-enhancement
